import fs from 'node:fs';
const SRC='C:/dev/scrape/out', OUT='C:/dev/NRMU/data';
const dec=s=>s.replace(/&#038;|&amp;/g,'&').replace(/&#8217;|&rsquo;/g,"’").replace(/&#8211;|&ndash;/g,'–').replace(/&#8220;|&#8221;/g,'"').replace(/&nbsp;/g,' ').replace(/&#8216;/g,'‘').replace(/&hellip;|&#8230;/g,'…').replace(/&#039;|&#8217;/g,"'");
const strip=h=>dec(h.replace(/<style[\s\S]*?<\/style>/g,'').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim());
const posts=JSON.parse(fs.readFileSync(`${SRC}/posts.json`,'utf8'));
const cats=JSON.parse(fs.readFileSync(`${SRC}/categories.json`,'utf8'));
const meta=posts.map(p=>{
  const html=p.content.rendered;
  const pdfs=[...html.matchAll(/href="([^"]+\.pdf)"/gi)].map(m=>m[1]);
  const img=(html.match(/<img[^>]+src="([^"]+)"/i)||[])[1]||null;
  fs.writeFileSync(`${OUT}/posts/${p.id}.json`,JSON.stringify({html}));
  const ex=strip(p.excerpt?.rendered||'')||strip(html);
  return {id:p.id,date:p.date.slice(0,10),slug:p.slug,title:dec(p.title.rendered),excerpt:ex.slice(0,220),cats:p.categories,pdfs:pdfs.length,pdf:pdfs[0]||null,img};
}).sort((a,b)=>b.date.localeCompare(a.date));
fs.writeFileSync(`${OUT}/index.json`,JSON.stringify(meta));
fs.writeFileSync(`${OUT}/categories.json`,JSON.stringify(cats.map(c=>({...c,name:dec(c.name)}))));
const pages=JSON.parse(fs.readFileSync(`${SRC}/pages.json`,'utf8')).filter(p=>p.content.rendered.length>50).map(p=>({id:p.id,slug:p.slug,title:dec(p.title.rendered),html:p.content.rendered}));
fs.writeFileSync(`${OUT}/pages.json`,JSON.stringify(pages));
console.log(meta.length,'posts',pages.length,'pages','with img',meta.filter(m=>m.img).length);
console.log(JSON.stringify(meta.slice(0,3),null,1));
